import EditorialHero from "../../components/common/EditorialHero.jsx";
import Section from "../../components/common/Section.jsx";
import SectionHeader from "../../components/common/SectionHeader.jsx";
import LeadershipCard from "../../components/company/LeadershipCard.jsx";
import Metric from "../../components/common/Metric.jsx";
import PageLoader from "../../components/feedback/PageLoader.jsx";
import ErrorState from "../../components/feedback/ErrorState.jsx";
import { useLeadership } from "../../queries/useContentQueries.js";
import { useLocale } from "../../i18n/LocaleContext.jsx";
import styles from "../shared/PageStyles.module.css";
export default function AboutPage(){const{locale}=useLocale();const fr=locale==="fr";const leadership=useLeadership(locale);if(leadership.isLoading)return <PageLoader/>;if(leadership.isError)return <ErrorState title={fr?"Impossible de charger la direction":"Could not load leadership"} onRetry={leadership.refetch}/>;const data=leadership.data??[];const principles=fr?["Comprendre le métier avant le paramétrage.","Rendre les responsabilités explicites.","Construire pour l’exploitation, pas seulement pour le go-live."]:["Understand the business before configuration.","Make ownership explicit.","Build for operations, not only go-live."];const metrics=fr?[{value:"01",label:"Un modèle opérationnel avant les décisions de module"},{value:"02",label:"Responsabilité système et contrats de données explicites"},{value:"03",label:"Maintenabilité après lancement comme exigence de conception"}]:[{value:"01",label:"One operating model before isolated module decisions"},{value:"02",label:"Explicit system ownership and data contracts"},{value:"03",label:"Maintainability after launch as a design requirement"}];return <><EditorialHero eyebrow={fr?"À propos de Prosperya":"About Prosperya"} title={fr?"Des systèmes d’entreprise pensés comme une architecture.":"Enterprise systems treated as architecture."} description={fr?"Prosperya est une société de conseil parisienne spécialisée dans la transformation ERP, NetSuite, les intégrations et l’automatisation.":"Prosperya is a Paris-based consultancy focused on ERP transformation, NetSuite, integrations and automation."}/><Section tone="soft"><div className={styles.detailIntro}><h2>{fr?"La philosophie.":"The philosophy."}</h2><div className={styles.detailList}>{principles.map((principle,index)=><div className={styles.detailRow} key={principle}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{principle}</h3></div></div>)}</div></div></Section><Section><SectionHeader eyebrow={fr?"Direction":"Leadership"} title={fr?"Une expertise senior proche des décisions.":"Senior expertise close to the decisions."}/>{data.map((person)=><LeadershipCard key={person.id} person={person}/>)}</Section><Section tone="soft"><SectionHeader eyebrow={fr?"Principes opérationnels":"Operating principles"} title={fr?"Peu de théâtre. Beaucoup de discipline.":"Low on theatre. High on discipline."}/><div className={styles.platformGrid}>{metrics.map((metric)=><Metric key={metric.value} metric={metric}/>)}</div></Section></>}
