// Approach page copy: how engagements are run, how we collaborate, what we hold to.
export const approachCopy = {
  en: {
    howEyebrow: "How we work",
    howTitle: "A disciplined process. Measurable outcomes.",
    practices: [
      ["users", "Governance", "Clear governance keeps alignment, transparency and risk management across the program.", ["Steering committees", "Decision frameworks", "Risk & issue management"]],
      ["sparkles", "Workshops", "Collaborative sessions to co-create solutions and align business and technology.", ["Design thinking", "Business & technical alignment", "Prioritization"]],
      ["layers", "Solution architecture", "Secure, scalable architectures aligned to your business and technology strategy.", ["Reference architecture", "Scalability & performance", "Security by design"]],
      ["wrench", "Build", "Agile delivery focused on quality, reusability and maintainability.", ["Sprint-based delivery", "Code quality", "Peer reviews"]],
      ["database", "Migration", "Proven migration frameworks minimize risk and protect data integrity.", ["Data cleansing", "Migration automation", "Validation & reconciliation"]],
      ["shield", "Validation", "Testing that proves functionality, performance and compliance.", ["End-to-end testing", "UAT & sign-off", "Performance & security"]],
      ["rocket", "Launch", "A structured go-live with hypercare for a smooth transition.", ["Operational readiness", "Hypercare support", "Monitoring & alerts"]],
      ["badge", "Adoption", "A people-first approach to engagement, capability and confidence.", ["Change management", "Training & enablement", "Stakeholder engagement"]],
      ["refresh", "Continuous improvement", "We stay to optimize, innovate and evolve with your business.", ["Performance reviews", "Enhancement backlog", "Innovation & automation"]],
    ],
    loop: "Continuous feedback loops across every phase to adapt, refine and maximize impact.",
    collabEyebrow: "Collaboration model",
    collabTitle: "Partners, not just providers.",
    collabPoints: ["Joint ownership of outcomes", "Transparent communication", "Aligned incentives", "Flexible engagement models"],
    collabNodes: [["Client leadership", "Vision & decisions"], ["Shared goals", "Outcomes & impact"], ["Continuous value", "Measure & improve"], ["Prosperya", "Expertise & execution"]],
    principlesEyebrow: "Delivery principles",
    principlesTitle: "The standards we never compromise.",
    principles: [
      ["target", "Outcome-driven", "Every decision ties back to measurable business value."],
      ["shield", "Quality by design", "Built right, tested thoroughly and secured by default."],
      ["search", "Transparency", "Open communication, clear reporting, no surprises."],
      ["refresh", "Adaptability", "Iterate fast, learn faster and adapt to change."],
      ["layers", "Sustainability", "Designed for scale, maintainability and longevity."],
    ],
  },
  fr: {
    howEyebrow: "Notre façon de travailler",
    howTitle: "Un processus rigoureux. Des résultats mesurables.",
    practices: [
      ["users", "Gouvernance", "Une gouvernance claire assure alignement, transparence et maîtrise des risques.", ["Comités de pilotage", "Cadres de décision", "Gestion des risques"]],
      ["sparkles", "Ateliers", "Des sessions collaboratives pour co-construire et aligner métier et technique.", ["Design thinking", "Alignement métier & technique", "Priorisation"]],
      ["layers", "Architecture de solution", "Des architectures sûres et évolutives, alignées sur votre stratégie.", ["Architecture de référence", "Évolutivité & performance", "Sécurité dès la conception"]],
      ["wrench", "Construction", "Une livraison agile centrée sur la qualité et la maintenabilité.", ["Livraison par sprints", "Qualité du code", "Revues croisées"]],
      ["database", "Migration", "Des méthodes éprouvées qui limitent le risque et protègent les données.", ["Nettoyage des données", "Migration automatisée", "Validation & rapprochement"]],
      ["shield", "Validation", "Des tests qui prouvent fonctionnalités, performance et conformité.", ["Tests de bout en bout", "Recette & validation", "Performance & sécurité"]],
      ["rocket", "Lancement", "Un démarrage structuré, avec hypercare pour une transition sereine.", ["Préparation opérationnelle", "Hypercare", "Supervision & alertes"]],
      ["badge", "Adoption", "Une approche centrée sur les personnes : engagement, compétences, confiance.", ["Conduite du changement", "Formation", "Engagement des parties prenantes"]],
      ["refresh", "Amélioration continue", "Nous restons pour optimiser, innover et évoluer avec vous.", ["Revues de performance", "Backlog d’améliorations", "Innovation & automatisation"]],
    ],
    loop: "Des boucles de retour continues à chaque phase pour ajuster, affiner et maximiser l’impact.",
    collabEyebrow: "Modèle de collaboration",
    collabTitle: "Des partenaires, pas seulement des prestataires.",
    collabPoints: ["Responsabilité partagée des résultats", "Communication transparente", "Intérêts alignés", "Modèles d’engagement flexibles"],
    collabNodes: [["Direction client", "Vision & décisions"], ["Objectifs communs", "Résultats & impact"], ["Valeur continue", "Mesurer & améliorer"], ["Prosperya", "Expertise & exécution"]],
    principlesEyebrow: "Principes de livraison",
    principlesTitle: "Les exigences sur lesquelles nous ne transigeons pas.",
    principles: [
      ["target", "Orientés résultats", "Chaque décision se rattache à une valeur métier mesurable."],
      ["shield", "Qualité dès la conception", "Bien construit, testé en profondeur, sécurisé par défaut."],
      ["search", "Transparence", "Une communication ouverte, un reporting clair, aucune surprise."],
      ["refresh", "Adaptabilité", "Itérer vite, apprendre plus vite, s’adapter au changement."],
      ["layers", "Durabilité", "Conçu pour l’échelle, la maintenabilité et la longévité."],
    ],
  },
};
