import { useParams } from "react-router-dom";
import EditorialHero from "../../components/common/EditorialHero.jsx";
import Section from "../../components/common/Section.jsx";
import SectionHeader from "../../components/common/SectionHeader.jsx";
import Metric from "../../components/common/Metric.jsx";
import PlatformCard from "../../components/platform/PlatformCard.jsx";
import ArchitectureComparison from "../../components/case-study/ArchitectureComparison.jsx";
import EmptyState from "../../components/feedback/EmptyState.jsx";
import PageLoader from "../../components/feedback/PageLoader.jsx";
import PrimaryLink from "../../components/common/PrimaryLink.jsx";
import { useCaseStudy, usePlatforms } from "../../queries/useContentQueries.js";
import { useLocale } from "../../i18n/LocaleContext.jsx";
import { useDocumentMeta } from "../../hooks/useDocumentMeta.js";
import styles from "../shared/PageStyles.module.css";
export default function CaseStudyPage(){const{slug}=useParams();const{locale}=useLocale();const fr=locale==="fr";const study=useCaseStudy(locale,slug);const platforms=usePlatforms(locale);const item=study.data;useDocumentMeta({title:item?`Prosperya — ${item.title}`:(fr?"Prosperya — Projets":"Prosperya — Work"),description:item?.description});if(study.isLoading)return <PageLoader/>;if(!item)return <Section><EmptyState title={fr?"Cas introuvable":"Case study not found"}/></Section>;const relatedPlatforms=(platforms.data??[]).filter((p)=>item.platformIds.includes(p.id));return <><EditorialHero eyebrow={item.category} title={item.title} description={item.description} aside={fr?"Structure illustrative V1 · Remplacer par des preuves client approuvées avant publication":"Illustrative V1 case-study structure · Replace with approved client evidence before publication"}/><Section><div className={styles.detailIntro}><h2>{fr?"Le contexte.":"The context."}</h2><p>{item.challenge}</p></div><div className={styles.detailList}><div className={styles.detailRow}><span>01 / {fr?"Défi":"Challenge"}</span><div><h3>{fr?"Complexité existante":"Existing complexity"}</h3><p>{item.challenge}</p></div></div><div className={styles.detailRow}><span>02 / Architecture</span><div><h3>{fr?"Intervention Prosperya":"Prosperya intervention"}</h3><p>{item.solution}</p></div></div><div className={styles.detailRow}><span>03 / {fr?"Résultat":"Outcome"}</span><div><h3>{fr?"Nouveau modèle":"New operating model"}</h3><p>{item.outcome}</p></div></div></div></Section><Section tone="soft"><SectionHeader eyebrow="Architecture" title={fr?"Du fragmenté à l’orchestré.":"From fragmented to orchestrated."}/><ArchitectureComparison locale={locale}/></Section><Section><SectionHeader eyebrow={fr?"Signaux de résultat":"Outcome signals"} title={fr?"Mesurer le changement opérationnel.":"Measure the operational change."}/><div className={styles.platformGrid}>{item.metrics.map((metric)=><Metric key={metric.id} metric={metric}/>)}</div></Section><Section tone="soft"><SectionHeader eyebrow={fr?"Paysage système":"System landscape"} title={fr?"Plateformes impliquées.":"Platforms in the architecture."}/><div className={styles.platformGrid}>{relatedPlatforms.map((platform)=><PlatformCard key={platform.id} platform={platform}/>)}</div></Section><Section><PrimaryLink to={`/${locale}/contact`}>{fr?"Démarrer une conversation similaire":"Start a similar conversation"}</PrimaryLink></Section></>}
