import { useParams } from "react-router-dom";
import EditorialHero from "../../components/common/EditorialHero.jsx";
import Section from "../../components/common/Section.jsx";
import SectionHeader from "../../components/common/SectionHeader.jsx";
import PrimaryLink from "../../components/common/PrimaryLink.jsx";
import PlatformCard from "../../components/platform/PlatformCard.jsx";
import CaseStudyCard from "../../components/case-study/CaseStudyCard.jsx";
import PageLoader from "../../components/feedback/PageLoader.jsx";
import EmptyState from "../../components/feedback/EmptyState.jsx";
import { useCapability, useCaseStudies, usePlatforms } from "../../queries/useContentQueries.js";
import { useLocale } from "../../i18n/LocaleContext.jsx";
import { useDocumentMeta } from "../../hooks/useDocumentMeta.js";
import styles from "../shared/PageStyles.module.css";
export default function ExpertiseDetailPage(){const{slug}=useParams();const{locale}=useLocale();const fr=locale==="fr";const capability=useCapability(locale,slug);const platforms=usePlatforms(locale);const studies=useCaseStudies(locale);const item=capability.data;useDocumentMeta({title:item?`Prosperya — ${item.eyebrow}`:"Prosperya — Expertise",description:item?.description});if(capability.isLoading)return <PageLoader/>;if(!item)return <Section><EmptyState title={fr?"Expertise introuvable":"Expertise not found"} description={fr?"Cette expertise n’existe pas ou n’est pas encore disponible.":"This capability does not exist or is not available yet."}/></Section>;const relatedPlatforms=(platforms.data??[]).filter((p)=>item.relatedPlatformIds.includes(p.id));const relatedStudies=(studies.data??[]).filter((s)=>item.relatedCaseStudyIds.includes(s.id));return <><EditorialHero eyebrow={`${item.number} / ${item.eyebrow}`} title={item.title} description={item.longDescription} aside={item.services.join(" · ")}/><Section><div className={styles.detailIntro}><h2>{fr?"Le problème avant la solution.":"The problem before the solution."}</h2><p>{item.description} {fr?"Chaque intervention commence par clarifier les responsabilités, les flux et la source de vérité avant de toucher à la configuration.":"Every engagement starts by clarifying ownership, flows and source-of-truth decisions before touching configuration."}</p></div><div className={styles.detailList}>{item.services.map((service,index)=><div className={styles.detailRow} key={service}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{service}</h3><p>{fr?"Décisions d’architecture explicites, mise en œuvre contrôlée et résultat mesurable.":"Explicit architecture decisions, controlled implementation and a measurable operational outcome."}</p></div></div>)}</div></Section><Section tone="soft"><SectionHeader eyebrow={fr?"Technologie":"Technology"} title={fr?"Plateformes liées à cette expertise.":"Platforms connected to this capability."}/><div className={styles.platformGrid}>{relatedPlatforms.map((platform)=><PlatformCard key={platform.id} platform={platform}/>)}</div></Section>{relatedStudies.length>0&&<Section><SectionHeader eyebrow={fr?"Projets liés":"Related work"} title={fr?"Voir l’architecture en contexte.":"See the architecture in context."}/>{relatedStudies.map((study,index)=><CaseStudyCard key={study.id} study={study} locale={locale} index={index}/>)}</Section>}<Section tone="soft"><SectionHeader eyebrow={fr?"Prochaine étape":"Next step"} title={fr?"Parlons du système réel.":"Let’s talk about the real system."} description={fr?"Pas de démo générique. Commencez par la complexité, les contraintes et l’architecture actuelle.":"No generic demo. Start with the complexity, constraints and current architecture."}/><PrimaryLink to={`/${locale}/contact`}>{fr?"Démarrer un projet":"Start a project"}</PrimaryLink></Section></>}
