import {
  BadgeCheck,
  Boxes,
  BrainCircuit,
  Building2,
  ChartColumn,
  Cloud,
  Cog,
  Compass,
  Database,
  Gauge,
  Landmark,
  Layers,
  LayoutGrid,
  LifeBuoy,
  Link2,
  Network,
  PencilRuler,
  RefreshCcw,
  Rocket,
  Search,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Target,
  Truck,
  Users,
  Warehouse,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

// Content refers to icons by stable name so CMS data never imports components.
const icons = {
  badge: BadgeCheck,
  boxes: Boxes,
  brain: BrainCircuit,
  building: Building2,
  cart: ShoppingCart,
  chart: ChartColumn,
  cloud: Cloud,
  cog: Cog,
  compass: Compass,
  database: Database,
  gauge: Gauge,
  grid: LayoutGrid,
  landmark: Landmark,
  layers: Layers,
  lifebuoy: LifeBuoy,
  link: Link2,
  network: Network,
  ruler: PencilRuler,
  refresh: RefreshCcw,
  rocket: Rocket,
  search: Search,
  share: Share2,
  shield: ShieldCheck,
  sparkles: Sparkles,
  target: Target,
  truck: Truck,
  users: Users,
  warehouse: Warehouse,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export default function SystemIcon({ name, size = 14, strokeWidth = 1.6 }) {
  const Icon = icons[name] ?? Sparkles;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
